### ISSUE TITLE
Fix Help Page Layout

### ISSUE THREAD

**Issue by BenJam** [mysociety/panama-theme#101]
The presence of the relevant law on various help page sections has shifted the focus somewhat, we need to remove it but provide a link/description to the law for those who are interested. 

Consider placing the name of the law, in smaller text, below each relevant section with a 'ver mas' button to expand the first paragraph of text and a 'ver lea' to link to the full text.

**Comment by zarino** [comment]
*Just to comment more clearly on this…*

The biggest issue with this page was the fully justified text:

![screen shot 2015-01-19 at 13 56 48](https://cloud.githubusercontent.com/assets/739624/5801454/0a88d682-9fe3-11e4-804b-312a0539a8ad.png)

While, in print documents, designers and copywriters can adjust spacing, add hyphens, and even sub-edit the content to make justified text work, online it's up to the web browser to do its best, and that usually means poor legibility, distracting "rivers" of whitespace, and slower reading times. Organisations like the RNIB in the UK strongly discourage use of justified text on the web.

I've just [pushed a fix](https://github.com/mysociety/panama-theme/commit/47f190644b02e88bf672ff0ca759786162b2f0dc) for the justification issue. It now looks more like this:

![screen shot 2015-01-19 at 13 26 48](https://cloud.githubusercontent.com/assets/739624/5801159/f0a74c42-9fdf-11e4-9cf9-97811794be98.png)

The second problem is the imbalance on some of the FAQs, between the short "human" answer and the much longer legal answer to the right. It breaks the flow of the page, and makes the content harder to parse. For example: the "What type of information that can be requested?" section has a human-friendly answer 3 lines long, beside a legal answer *over 150 lines long*.

I'm going to have a go at finding a good balance, as @BenJam suggested, between completely removing the legal text (which would be a shame, since we can't link directly to the sections in question because they're locked away in PDFs) and leaving it as-is. Watch this space.

**Comment by zarino** [comment]
Ok, as of https://github.com/mysociety/panama-theme/commit/915c337fd067b36a6c7a9d9cfc1aef9c47eb9d04, legal passages are truncated after the first paragraph, with a link to reveal the full passage in place:

![screen shot 2015-01-19 at 14 55 12](https://cloud.githubusercontent.com/assets/739624/5802279/4f480420-9feb-11e4-963a-3d8ed4ae553b.png)

The JavaScript makes no attempt to shorten the first paragraph if it’s a long one, because that's a world of pain.
