### ISSUE TITLE
provide translations & remove UK specific guidance from 'refused' process

### ISSUE THREAD

**Issue by BenJam** [mysociety/panama-theme#109]
If my request has been refused and I select this option as a requestor I'm taken to a page, in english, about steps that can be taken next, including how to contact the Information Commissioners office.

This page needs to be changed to provide guidance for:
- raising an internal review
- forwarding the case to ANTAI

This needs to be done before launch.

**Comment by stevenday** [comment]
I've found the page template in question and placed it into the Panama theme in order to make it possible to change it. I've made a few initial edits, but obviously we now need a Spanish and proper English version of the text. 

Here's how it looks now:
![unhappy_page](https://cloud.githubusercontent.com/assets/663700/6525745/43ac87a0-c401-11e4-81c8-e3a61c69b7a4.png)

@BenJam - can you pass this to Panama to get the copy?

**Comment by stevenday** [comment]
The full erb template is here: https://github.com/mysociety/panama-theme/blob/0772e102858eb1ed73794416ff216bc3fc1f1055/lib/views/help/unhappy.en.html.erb

**Comment by stevenday** [comment]
This is now up on the staging site.
